# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: storage.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstorage.proto\x12\x07storage\"2\n\rUploadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"2\n\x0eUploadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"#\n\x0f\x44ownloadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"E\n\x10\x44ownloadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\x32\x89\x01\n\x0b\x46ileStorage\x12\x39\n\x06Upload\x12\x16.storage.UploadRequest\x1a\x17.storage.UploadResponse\x12?\n\x08\x44ownload\x12\x18.storage.DownloadRequest\x1a\x19.storage.DownloadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADREQUEST']._serialized_start=26
  _globals['_UPLOADREQUEST']._serialized_end=76
  _globals['_UPLOADRESPONSE']._serialized_start=78
  _globals['_UPLOADRESPONSE']._serialized_end=128
  _globals['_DOWNLOADREQUEST']._serialized_start=130
  _globals['_DOWNLOADREQUEST']._serialized_end=165
  _globals['_DOWNLOADRESPONSE']._serialized_start=167
  _globals['_DOWNLOADRESPONSE']._serialized_end=236
  _globals['_FILESTORAGE']._serialized_start=239
  _globals['_FILESTORAGE']._serialized_end=376
# @@protoc_insertion_point(module_scope)
